import 'package:cloud_firestore/cloud_firestore.dart';

class Lineup {
  final String             lineupId;
  final String             eventId;
  final String             teamId;
  /// position label → userId (empty string = unassigned). Used for single-team events.
  final Map<String, String> assignments;
  /// Sub-team rosters for multi-team events (numSubTeams > 1).
  /// Each entry is a position→userId map for one sub-team. Empty for single-team.
  final List<Map<String, String>> subTeams;
  final bool               autoGenerated;
  final DateTime           createdAt;

  const Lineup({
    required this.lineupId,
    required this.eventId,
    required this.teamId,
    required this.assignments,
    this.subTeams = const [],
    required this.autoGenerated,
    required this.createdAt,
  });

  factory Lineup.fromFirestore(DocumentSnapshot doc) {
    final d = doc.data() as Map<String, dynamic>;
    return Lineup(
      lineupId:      doc.id,
      eventId:       d['eventId']      as String? ?? '',
      teamId:        d['teamId']       as String? ?? '',
      assignments:   Map<String, String>.from(d['assignments'] as Map? ?? {}),
      subTeams:      (d['subTeams'] as List<dynamic>?)
              ?.map((e) => Map<String, String>.from(e as Map))
              .toList() ??
          [],
      autoGenerated: d['autoGenerated'] as bool? ?? false,
      createdAt:     (d['createdAt'] as Timestamp?)?.toDate() ?? DateTime.now(),
    );
  }

  Map<String, dynamic> toFirestore() => {
    'eventId':       eventId,
    'teamId':        teamId,
    'assignments':   assignments,
    if (subTeams.isNotEmpty) 'subTeams': subTeams,
    'autoGenerated': autoGenerated,
    'createdAt':     Timestamp.fromDate(createdAt),
  };

  int get assignedCount =>
      assignments.values.where((v) => v.isNotEmpty).length;
}
