import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import '../../../../core/config/app_config.dart';
import '../../../../core/services/export_service.dart';
import '../../../../core/services/rewarded_ad_service.dart';
import '../../../shared/providers/ads_provider.dart';
import '../../../../core/services/lineup_generator.dart';
import '../../../../features/auth/data/user_repository.dart';
import '../../../../features/auth/presentation/providers/auth_provider.dart';
import '../../../../features/events/domain/event.dart';
import '../../../../features/events/presentation/providers/events_provider.dart';
import '../../../../features/rankings/data/ranking_repository.dart';
import '../../../../features/rankings/domain/ranking.dart';
import '../../../../features/teams/domain/team.dart';
import '../../../../features/teams/presentation/providers/teams_provider.dart';
import '../../data/lineup_repository.dart';
import '../../domain/lineup.dart';
import '../providers/lineup_provider.dart';
import '../providers/player_preference_provider.dart';

class LineupScreen extends ConsumerStatefulWidget {
  final String teamId;
  final String eventId;
  const LineupScreen({super.key, required this.teamId, required this.eventId});

  @override
  ConsumerState<LineupScreen> createState() => _LineupScreenState();
}

class _LineupScreenState extends ConsumerState<LineupScreen> {
  // Single-team draft: position → userId ('' = unassigned)
  Map<String, String> _draft = {};
  // Multi-team drafts: one map per sub-team
  List<Map<String, String>> _subTeamDrafts = [];
  bool _initialized    = false;
  bool _saving         = false;
  bool _autoGenerated  = false; // tracks whether ad is owed on save

  void _initDraft(Lineup? saved, List<String> positions, int numSubTeams) {
    // Skip if already initialized for this configuration
    if (_initialized) {
      if (numSubTeams <= 1 && _subTeamDrafts.isEmpty) return;
      if (numSubTeams > 1 && _subTeamDrafts.length == numSubTeams) return;
    }
    _initialized = true;

    if (numSubTeams <= 1) {
      _draft = {for (final p in positions) p: saved?.assignments[p] ?? ''};
      _subTeamDrafts = [];
    } else {
      _draft = {};
      final saved_ = saved?.subTeams ?? [];
      _subTeamDrafts = List.generate(numSubTeams, (i) {
        final m = i < saved_.length ? saved_[i] : <String, String>{};
        return {for (final p in positions) p: m[p] ?? ''};
      });
    }
  }

  Future<void> _save() async {
    // Show rewarded ad now (after user has seen the lineup) rather than
    // blocking auto-generate upfront.
    if (_autoGenerated && AppConfig.enableRewardedAds) {
      final adFree = ref.read(adFreeProvider);
      if (!adFree) {
        final earned = await RewardedAdService.showAndAwaitReward();
        if (!earned) {
          if (mounted) {
            ScaffoldMessenger.of(context).showSnackBar(
              const SnackBar(content: Text('Watch the full ad to save the auto-generated lineup.')),
            );
          }
          return;
        }
      }
    }

    setState(() => _saving = true);
    final lineup = Lineup(
      lineupId:      widget.eventId,
      eventId:       widget.eventId,
      teamId:        widget.teamId,
      assignments:   _subTeamDrafts.isEmpty ? Map.from(_draft) : {},
      subTeams:      _subTeamDrafts.map((m) => Map<String, String>.from(m)).toList(),
      autoGenerated: _autoGenerated,
      createdAt:     DateTime.now(),
    );
    await ref.read(lineupRepositoryProvider).saveLineup(lineup);
    if (mounted) {
      setState(() { _saving = false; _autoGenerated = false; });
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Lineup saved.')),
      );
    }
  }

  void _clearAll() => setState(() {
    if (_subTeamDrafts.isNotEmpty) {
      for (int i = 0; i < _subTeamDrafts.length; i++) {
        _subTeamDrafts[i] = {for (final k in _subTeamDrafts[i].keys) k: ''};
      }
      return;
    }
    _draft = {for (final k in _draft.keys) k: ''};
  });

  Future<void> _saveTemplate(String teamId, String sport) async {
    await ref.read(lineupRepositoryProvider).saveTemplate(teamId, sport, _draft);
    if (mounted) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Template saved for this sport.')));
    }
  }

  Future<void> _loadTemplate(String teamId, String sport, List<String> roster) async {
    final template = await ref.read(lineupRepositoryProvider)
        .loadTemplate(teamId, sport);
    if (template == null) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text('No saved template for this sport yet.')));
      }
      return;
    }
    // Only apply assignments for UIDs still on the roster
    setState(() {
      for (final pos in _draft.keys) {
        final uid = template[pos] ?? '';
        _draft[pos] = roster.contains(uid) ? uid : '';
      }
    });
    if (mounted) {
      final filled = _draft.values.where((v) => v.isNotEmpty).length;
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text('Template loaded — $filled positions filled.')));
    }
  }

  Future<void> _exportPdf(BuildContext context, WidgetRef ref, Team team) async {
    final eventAsync = ref.read(eventProvider(widget.eventId));
    final event = eventAsync.valueOrNull;

    // Resolve all assigned UIDs to names
    final userRepo = ref.read(userRepositoryProvider);
    final namedAssignments = <String, String>{};
    for (final entry in _draft.entries) {
      if (entry.value.isNotEmpty) {
        final user = await userRepo.getUser(entry.value);
        namedAssignments[entry.key] =
            user?.name.isNotEmpty == true ? user!.name : entry.value;
      } else {
        namedAssignments[entry.key] = '';
      }
    }

    await ExportService.shareLineupPdf(
      teamName:   team.name,
      sport:      team.sport,
      eventLabel: event?.type.label ?? 'Event',
      eventDate:  event?.date ?? DateTime.now(),
      assignments: namedAssignments,
    );
  }

  Future<void> _autoGenerate(
      BuildContext context, WidgetRef ref, Team team) async {
    final positions     = AppConfig.positionsForSport(team.sport);
    final availList     = ref.read(eventAvailabilityProvider((widget.eventId, widget.teamId))).valueOrNull ?? [];
    final rankMap       = ref.read(_teamRankingsMapProvider(team.teamId)).valueOrNull ?? {};
    final prefMap       = ref.read(teamPreferencesMapProvider(team.teamId)).valueOrNull ?? {};
    final numSubTeams   = ref.read(eventProvider(widget.eventId)).valueOrNull?.numSubTeams ?? 1;

    // Only include players who said yes or maybe
    final availableUids = availList
        .where((a) => a.response.name == 'yes' || a.response.name == 'maybe')
        .map((a) => a.userId)
        .where((uid) => team.players.contains(uid) || team.admins.contains(uid))
        .toList();

    if (availableUids.isEmpty) {
      if (context.mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text('No players have RSVPed yes or maybe for this event.')),
        );
      }
      return;
    }

    if (numSubTeams > 1) {
      final generated = LineupGenerator.generateSubTeams(
        numSubTeams:   numSubTeams,
        positions:     positions,
        availableUids: availableUids,
        rankings:      rankMap,
        preferences:   prefMap,
        sport:         team.sport,
      );
      setState(() { _subTeamDrafts = generated; _autoGenerated = true; });
      if (context.mounted) {
        final filled = generated.fold<int>(
            0, (acc, m) => acc + m.values.where((v) => v.isNotEmpty).length);
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text(
            'Auto-generated: $filled/${numSubTeams * positions.length} positions filled. '
            'Review and save.')),
        );
      }
    } else {
      final generated = LineupGenerator.generate(
        positions:     positions,
        availableUids: availableUids,
        rankings:      rankMap,
        preferences:   prefMap,
        sport:         team.sport,
      );
      setState(() { _draft = {..._draft, ...generated}; _autoGenerated = true; });
      if (context.mounted) {
        final filled = generated.values.where((v) => v.isNotEmpty).length;
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text(
            'Auto-generated: $filled/${positions.length} positions filled. '
            'Review and save.')),
        );
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    final teamAsync   = ref.watch(teamProvider(widget.teamId));
    final lineupAsync = ref.watch(lineupProvider(widget.eventId));
    final eventAsync  = ref.watch(eventProvider(widget.eventId));
    final uid         = ref.watch(currentUserProvider)?.uid ?? '';
    final isAdmin     = teamAsync.valueOrNull?.isAdmin(uid) ?? false;
    final numSubTeams = eventAsync.valueOrNull?.numSubTeams ?? 1;

    // Yes/maybe RSVPs — used to filter the player picker to attending players only
    final availList = ref.watch(
        eventAvailabilityProvider((widget.eventId, widget.teamId))).valueOrNull ?? [];
    final yesUids = availList
        .where((a) => a.response.name == 'yes' || a.response.name == 'maybe')
        .map((a) => a.userId)
        .toSet();

    return teamAsync.when(
      loading: () => const Scaffold(body: Center(child: CircularProgressIndicator())),
      error:   (e, _) => Scaffold(body: Center(child: Text('Error: $e'))),
      data: (team) {
        if (team == null) return const Scaffold(body: Center(child: Text('Team not found.')));

        final positions = AppConfig.positionsForSport(team.sport);

        return lineupAsync.when(
          loading: () => const Scaffold(body: Center(child: CircularProgressIndicator())),
          error:   (e, _) => Scaffold(body: Center(child: Text('Error: $e'))),
          data: (saved) {
            _initDraft(saved, positions, numSubTeams);

            // ── Save bar ──────────────────────────────────────────────────
            Widget? saveBar;
            if (isAdmin) {
              final int assigned;
              final int total;
              if (numSubTeams <= 1) {
                assigned = _draft.values.where((v) => v.isNotEmpty).length;
                total    = _draft.length;
              } else {
                assigned = _subTeamDrafts.fold(0,
                    (acc, m) => acc + m.values.where((v) => v.isNotEmpty).length);
                total = numSubTeams * positions.length;
              }
              saveBar = SafeArea(
                child: Padding(
                  padding: const EdgeInsets.all(16),
                  child: FilledButton(
                    onPressed: _saving ? null : _save,
                    child: _saving
                        ? const SizedBox(
                            height: 20, width: 20,
                            child: CircularProgressIndicator(strokeWidth: 2))
                        : Text('$assigned/$total assigned — Save Lineup'),
                  ),
                ),
              );
            }

            // ── AppBar actions (same for single and multi-team) ───────────
            final appBarActions = <Widget>[
              if (isAdmin) ...[
                TextButton(onPressed: _clearAll, child: const Text('Clear')),
                if (AppConfig.enableAutoLineup)
                  IconButton(
                    icon: const Icon(Icons.auto_awesome),
                    tooltip: 'Auto-generate lineup',
                    onPressed: () => _autoGenerate(context, ref, team),
                  ),
                if (numSubTeams <= 1)
                  PopupMenuButton<String>(
                    icon: const Icon(Icons.more_vert),
                    tooltip: 'More options',
                    onSelected: (v) {
                      final roster = [...team.admins, ...team.players];
                      if (v == 'load_template') {
                        _loadTemplate(team.teamId, team.sport, roster);
                      } else if (v == 'save_template') {
                        _saveTemplate(team.teamId, team.sport);
                      } else if (v == 'export_pdf') {
                        _exportPdf(context, ref, team);
                      }
                    },
                    itemBuilder: (_) => const [
                      PopupMenuItem(
                        value: 'load_template',
                        child: ListTile(
                          leading: Icon(Icons.upload_outlined),
                          title: Text('Load template'),
                          contentPadding: EdgeInsets.zero,
                        ),
                      ),
                      PopupMenuItem(
                        value: 'save_template',
                        child: ListTile(
                          leading: Icon(Icons.save_outlined),
                          title: Text('Save as template'),
                          contentPadding: EdgeInsets.zero,
                        ),
                      ),
                      PopupMenuItem(
                        value: 'export_pdf',
                        child: ListTile(
                          leading: Icon(Icons.picture_as_pdf_outlined),
                          title: Text('Export PDF'),
                          contentPadding: EdgeInsets.zero,
                        ),
                      ),
                    ],
                  ),
              ],
            ];

            // ── Single-team layout ────────────────────────────────────────
            if (numSubTeams <= 1) {
              final uidToPos = <String, String>{
                for (final e in _draft.entries) if (e.value.isNotEmpty) e.value: e.key,
              };
              return Scaffold(
                appBar: AppBar(title: const Text('Lineup'), actions: appBarActions),
                body: ListView.separated(
                  padding: const EdgeInsets.fromLTRB(16, 12, 16, 100),
                  itemCount: positions.length,
                  separatorBuilder: (_, __) => const Divider(height: 1),
                  itemBuilder: (_, i) {
                    final position    = positions[i];
                    final assignedUid = _draft[position] ?? '';
                    return _PositionTile(
                      position:    position,
                      assignedUid: assignedUid,
                      team:        team,
                      isAdmin:     isAdmin,
                      uidToPos:    uidToPos,
                      yesUids:     yesUids,
                      onAssign: isAdmin
                          ? (uid) => setState(() {
                              if (uid.isNotEmpty) {
                                _draft.updateAll((k, v) =>
                                    v == uid && k != position ? '' : v);
                              }
                              _draft[position] = uid;
                            })
                          : null,
                    );
                  },
                ),
                bottomNavigationBar: saveBar,
              );
            }

            // ── Multi-team layout (tabs) ───────────────────────────────────
            return DefaultTabController(
              length: numSubTeams,
              child: Scaffold(
                appBar: AppBar(
                  title: const Text('Lineup'),
                  actions: appBarActions,
                  bottom: TabBar(
                    tabs: List.generate(
                      numSubTeams,
                      (i) => Tab(text: 'Team ${i + 1}'),
                    ),
                  ),
                ),
                body: TabBarView(
                  children: List.generate(numSubTeams, (teamIdx) {
                    // Ensure draft list is long enough (safety guard)
                    while (_subTeamDrafts.length <= teamIdx) {
                      _subTeamDrafts.add({for (final p in positions) p: ''});
                    }
                    final teamDraft = _subTeamDrafts[teamIdx];
                    final uidToPos  = <String, String>{
                      for (final e in teamDraft.entries)
                        if (e.value.isNotEmpty) e.value: e.key,
                    };
                    return ListView.separated(
                      padding: const EdgeInsets.fromLTRB(16, 12, 16, 100),
                      itemCount: positions.length,
                      separatorBuilder: (_, __) => const Divider(height: 1),
                      itemBuilder: (_, i) {
                        final position    = positions[i];
                        final assignedUid = teamDraft[position] ?? '';
                        return _PositionTile(
                          position:    position,
                          assignedUid: assignedUid,
                          team:        team,
                          isAdmin:     isAdmin,
                          uidToPos:    uidToPos,
                          yesUids:     yesUids,
                          onAssign: isAdmin
                              ? (uid) => setState(() {
                                  if (uid.isNotEmpty) {
                                    teamDraft.updateAll((k, v) =>
                                        v == uid && k != position ? '' : v);
                                  }
                                  teamDraft[position] = uid;
                                })
                              : null,
                        );
                      },
                    );
                  }),
                ),
                bottomNavigationBar: saveBar,
              ),
            );
          },
        );
      },
    );
  }
}

// ── Position tile ──────────────────────────────────────────────────────────────

class _PositionTile extends ConsumerWidget {
  final String         position;
  final String         assignedUid;
  final Team           team;
  final bool           isAdmin;
  final Map<String, String> uidToPos; // uid → position name for already-placed display
  final Set<String>    yesUids;       // yes/maybe RSVPs for picker filtering
  final ValueChanged<String>? onAssign;

  const _PositionTile({
    required this.position,
    required this.assignedUid,
    required this.team,
    required this.isAdmin,
    required this.uidToPos,
    required this.yesUids,
    required this.onAssign,
  });

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final nameAsync = assignedUid.isNotEmpty
        ? ref.watch(_userNameProvider(assignedUid))
        : null;
    final assignedName = nameAsync?.valueOrNull;

    return ListTile(
      leading: ExcludeSemantics(
        child: CircleAvatar(
          backgroundColor: assignedUid.isNotEmpty
              ? Theme.of(context).colorScheme.primaryContainer
              : Theme.of(context).colorScheme.surfaceContainerHighest,
          child: Text(
            position.substring(0, 1),
            style: TextStyle(
                color: assignedUid.isNotEmpty
                    ? Theme.of(context).colorScheme.onPrimaryContainer
                    : Theme.of(context).colorScheme.outline),
          ),
        ),
      ),
      title:    Text(position),
      subtitle: Text(
        assignedUid.isNotEmpty
            ? (assignedName ?? assignedUid)
            : 'Unassigned',
        style: TextStyle(
            color: assignedUid.isEmpty
                ? Theme.of(context).colorScheme.outline
                : null),
      ),
      trailing: isAdmin
          ? IconButton(
              icon: const Icon(Icons.swap_horiz),
              tooltip: 'Assign player',
              onPressed: () => _showPlayerPicker(context, ref),
            )
          : null,
    );
  }

  void _showPlayerPicker(BuildContext context, WidgetRef ref) {
    showModalBottomSheet(
      context:    context,
      isScrollControlled: true,
      builder:    (_) => _PlayerPickerSheet(
        team:        team,
        position:    position,
        currentUid:  assignedUid,
        uidToPos:    uidToPos,
        yesUids:     yesUids,
        onSelect:    onAssign!,
      ),
    );
  }
}

// ── Player picker bottom sheet ─────────────────────────────────────────────────

class _PlayerPickerSheet extends ConsumerWidget {
  final Team   team;
  final String position, currentUid;
  final Map<String, String> uidToPos; // uid → position name for already-placed display
  final Set<String>         yesUids;  // yes/maybe RSVPs for filtering
  final ValueChanged<String> onSelect;

  const _PlayerPickerSheet({
    required this.team,
    required this.position,
    required this.currentUid,
    required this.uidToPos,
    required this.yesUids,
    required this.onSelect,
  });

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final rankingsAsync = ref.watch(_teamRankingsMapProvider(team.teamId));
    final rankMap = rankingsAsync.valueOrNull ?? {};

    // Only include players who said yes/maybe (plus whoever is already in this slot)
    final eligible = [...team.admins, ...team.players]
        .where((u) => yesUids.contains(u) || u == currentUid)
        .toList()
      ..sort((a, b) {
          final ra = rankMap[a]?.score ?? 0.0;
          final rb = rankMap[b]?.score ?? 0.0;
          return rb.compareTo(ra);
        });

    // Split into available (not placed elsewhere) and already placed
    final available = eligible
        .where((u) => !uidToPos.containsKey(u) || u == currentUid)
        .toList();
    final placed = eligible
        .where((u) => uidToPos.containsKey(u) && u != currentUid)
        .toList();

    Widget memberTile(String uid, {String? placedAt}) {
      final ranking   = rankMap[uid];
      final nameAsync = ref.watch(_userNameProvider(uid));
      final name      = nameAsync.valueOrNull ?? uid;
      final subtitle  = placedAt;
      return ListTile(
        leading: Semantics(
          label: ranking != null
              ? 'Rating ${ranking.scoreLabel}'
              : 'Unrated',
          child: ExcludeSemantics(
            child: CircleAvatar(
              backgroundColor: placedAt != null
                  ? Theme.of(context).colorScheme.surfaceContainerHighest
                  : ranking != null
                      ? _scoreColor(ranking.score, context)
                      : null,
              child: Text(
                ranking?.scoreLabel ?? '?',
                style: TextStyle(
                    color: placedAt != null
                        ? Theme.of(context).colorScheme.outline
                        : Colors.white,
                    fontSize: 13,
                    fontWeight: FontWeight.bold),
              ),
            ),
          ),
        ),
        title: Text(name,
            style: TextStyle(
                color: placedAt != null
                    ? Theme.of(context).colorScheme.onSurface.withOpacity(0.75)
                    : null)),
        subtitle: subtitle != null ? Text(subtitle) : null,
        selected: uid == currentUid,
        onTap: () {
          onSelect(uid);
          Navigator.of(context).pop();
        },
      );
    }

    return DraggableScrollableSheet(
      initialChildSize: 0.6,
      maxChildSize:     0.9,
      minChildSize:     0.4,
      expand: false,
      builder: (_, sc) => Column(
        children: [
          Padding(
            padding: const EdgeInsets.fromLTRB(16, 16, 16, 8),
            child: Text('Assign to $position',
                style: Theme.of(context).textTheme.titleMedium),
          ),
          const Divider(),
          Expanded(
            child: ListView(
              controller: sc,
              children: [
                // Unassign option
                ListTile(
                  leading: const CircleAvatar(child: Icon(Icons.person_off)),
                  title:   const Text('Unassigned'),
                  selected: currentUid.isEmpty,
                  onTap: () {
                    onSelect('');
                    Navigator.of(context).pop();
                  },
                ),
                const Divider(height: 1),

                // Available section
                if (available.isNotEmpty) ...[
                  Padding(
                    padding: const EdgeInsets.fromLTRB(16, 12, 16, 4),
                    child: Text('Available (${available.length})',
                        style: Theme.of(context).textTheme.labelMedium?.copyWith(
                            color: Theme.of(context).colorScheme.primary)),
                  ),
                  for (final uid in available) memberTile(uid),
                ],

                // Already placed section
                if (placed.isNotEmpty) ...[
                  const Divider(height: 1),
                  Padding(
                    padding: const EdgeInsets.fromLTRB(16, 12, 16, 4),
                    child: Text('Already placed (${placed.length})',
                        style: Theme.of(context).textTheme.labelMedium?.copyWith(
                            color: Theme.of(context).colorScheme.outline)),
                  ),
                  for (final uid in placed) memberTile(uid, placedAt: uidToPos[uid]),
                ],
              ],
            ),
          ),
        ],
      ),
    );
  }

  Color _scoreColor(double score, BuildContext context) {
    if (score >= 7) return Colors.green.shade600;
    if (score >= 4) return Colors.orange.shade600;
    return Colors.red.shade400;
  }
}

// ── Cached providers ───────────────────────────────────────────────────────────

final _userNameProvider = FutureProvider.family<String, String>((ref, uid) async {
  final user = await ref.read(userRepositoryProvider).getUser(uid);
  return user?.name.isNotEmpty == true ? user!.name : uid;
});

final _teamRankingsMapProvider =
    StreamProvider.family<Map<String, Ranking>, String>((ref, teamId) {
  return ref.read(rankingRepositoryProvider).watchTeamRankings(teamId).map(
    (list) => {for (final r in list) r.userId: r},
  );
});
